export type ImageRecord = {
  id: string;
  file?: File | null;
  name: string;
  baseName: string;
  src: string;
  width: number;
  height: number;
  sizeKb: string;
  imgElement: unknown;
};

export const baseNameOf = (name: string): string =>
  name.substring(0, name.lastIndexOf('.')) || name;

export type RawImageLoad = {
  id: string;
  name: string;
  size: number;
  src: string;
  naturalWidth: number;
  naturalHeight: number;
  width: number;
  height: number;
  imgElement: unknown;
};

/** Build the gallery record from a finished image load (pure; id generated by caller). */
export const createImageRecord = (p: RawImageLoad): ImageRecord => ({
  id: p.id,
  name: p.name,
  baseName: baseNameOf(p.name),
  src: p.src,
  width: p.naturalWidth || p.width,
  height: p.naturalHeight || p.height,
  sizeKb: (p.size / 1024).toFixed(1),
  imgElement: p.imgElement,
});
